name: Fuzzer Create Issue

on:
  repository_dispatch:
    types: [ fuzzer-issue ]

jobs:
  create-issue:
    name: Create Dolt Issue found by Dolthub/Fuzzer
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/github-script@v4
        env:
          ASSIGNEE: ${{ github.event.client_payload.assignee }}
          URL: ${{ github.event.client_payload.url }}
          BODY: ${{ github.event.client_payload.errors }}
          VERSION: ${{ github.event.client_payload.dolt_version }}
        with:
          script: |
            try {
              const { ASSIGNEE, URL, VERSION, BODY } = process.env;
              const { owner, repo } = context.repo;

              const DELIMITER = "`"
              const CODEDELIMITER = "```"
              const body = `An error was encountered for Dolt ${DELIMITER}${VERSION}${DELIMITER}\nAssets are located at:\n${URL}\n${CODEDELIMITER}\n${BODY}\n${CODEDELIMITER}`;

              await github.issues.create({
                title: "Fuzzer found Dolt issue",
                owner,
                repo,
                assignee: ASSIGNEE,
                body,
              });

              process.exit(0);
            } catch (err) {
              console.log("Error:", err);
              process.exit(1);
            }
